apiVersion: v1
kind: Service
metadata:
  name: sandbox-server
  labels:
    app: sandbox-server
spec:
  selector:
    app: sandbox-server
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  type: ClusterIP
